<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Untitled 1</title>
</head>

<body>
<xml>
<NATION>
<NAME>Babylatia</NAME>
<TYPE>OOC Primal Era</TYPE>
<FULLNAME>The OOC Primal Era of Babylatia</FULLNAME>
<MOTTO>المعرفة هي السيف. (Knowledge is the sword.)</MOTTO>
<CATEGORY>Capitalizt</CATEGORY>
<UNSTATUS>WA Member</UNSTATUS>
<FREEDOM>
<CIVILRIGHTS>Superb</CIVILRIGHTS>
<ECONOMY>All-Consuming</ECONOMY>
<POLITICALFREEDOM>Average</POLITICALFREEDOM>
</FREEDOM>
<REGION>Renegade Islands Alliance</REGION>
<POPULATION>1467</POPULATION>
<TAX>55</TAX>
<ANIMAL>Pachycephalosaur</ANIMAL>
<CURRENCY>Bytik</CURRENCY>
<DEMONYM>Babylaen</DEMONYM>
<DEMONYM2>Babylae</DEMONYM2>
<DEMONYM2PLURAL>Babylae'i</DEMONYM2PLURAL>
<FLAG>
http://www.nationstates.net/images/flags/uploads/babylatia__442601.png
</FLAG><MAJORINDUSTRY>Information Technology</MAJORINDUSTRY><GOVTPRIORITY>Law & Order</GOVTPRIORITY><GOVT><ADMINISTRATION>3.1</ADMINISTRATION><DEFENCE>21.2</DEFENCE><EDUCATION>17.8</EDUCATION><ENVIRONMENT>14.3</ENVIRONMENT><HEALTHCARE>4.2</HEALTHCARE><COMMERCE>9.3</COMMERCE><LAWANDORDER>21.2</LAWANDORDER><PUBLICTRANSPORT>8.9</PUBLICTRANSPORT><SOCIALEQUALITY>0.0</SOCIALEQUALITY><SPIRITUALITY>0.0</SPIRITUALITY><WELFARE>0.0</WELFARE></GOVT><FOUNDED>251 days ago</FOUNDED><FIRSTLOGIN>1392522125</FIRSTLOGIN><LASTLOGIN>1414246363</LASTLOGIN><LASTACTIVITY>3 hours ago</LASTACTIVITY><INFLUENCE>Minnow</INFLUENCE><FREEDOMSCORES><CIVILRIGHTS>75</CIVILRIGHTS><ECONOMY>96</ECONOMY><POLITICALFREEDOM>56</POLITICALFREEDOM></FREEDOMSCORES><PUBLICSECTOR>43.0</PUBLICSECTOR><DEATHS><CAUSE type="Lost in Wilderness">14.8</CAUSE><CAUSE type="Exposure">17.0</CAUSE><CAUSE type="Suicide While in Police Custody">0.8</CAUSE><CAUSE type="Heart Disease">20.8</CAUSE><CAUSE type="Old Age">46.6</CAUSE></DEATHS><LEADER>Kaeto Ashwar</LEADER><CAPITAL>Mana</CAPITAL><RELIGION>Pain</RELIGION><FACTBOOKS>7</FACTBOOKS><DISPATCHES>11</DISPATCHES></NATION></xml>
</body>

</html>
